### ISSUE TITLE
Batched Inserts

### ISSUE THREAD

**Issue by Stono** [featurist/sworm#1]
Nice work mate, promise based too.
Would be sweet if inserts in one to many relationships were batched, ie:

INSERT INTO table (cols)
Values
(row1), (row2), (row3)

Id take a crack myself but crazy busy, if you happened to do this in the interim i'd owe you one :-)

**Comment by refractalize** [comment]
Sounds like a good idea, but I'm going to close this until there's more demand for it. (PRs welcome!)
