### ISSUE TITLE
Binary Data

### ISSUE THREAD

**Issue by jsphadetula** [featurist/sworm#13]
How to write binary data using model objects. It only works with plain queries

**Comment by refractalize** [comment]
Not sure really, different drivers have different mechanisms for this. I suggest looking at the driver documentation for what you're trying to do, and possibly resort to using the driver direct.

Which DB are you using, perhaps I can help?

**Comment by jsphadetula** [comment]
ms sql server 


Get Outlook for Android






On Tue, Jul 12, 2016 at 12:51 PM +0100, "Tim Macfarlane" <notifications@github.com> wrote:












Not sure really, different drivers have different mechanisms for this. I suggest looking at the driver documentation for what you're trying to do, and possibly resort to using the driver direct.



Which DB are you using, perhaps I can help?

**Comment by refractalize** [comment]
Looks like you can just pass a node `Buffer` and it will map to a `VarBinary` in MS SQL.

See: https://github.com/patriksimek/node-mssql/blob/817a555a37204edb63067967ae8f5b4b7e7491e3/README.md#input-name-type-value

Haven't used it myself but it looks like it will just work.

**Comment by jsphadetula** [comment]
Have tried that not working 


Get Outlook for Android






On Tue, Jul 12, 2016 at 3:39 PM +0100, "Tim Macfarlane" <notifications@github.com> wrote:












Looks like you can just pass a node Buffer and it will map to a VarBinary in MS SQL.



See: https://github.com/patriksimek/node-mssql/blob/817a555a37204edb63067967ae8f5b4b7e7491e3/README.md#input-name-type-value



Haven't used it myself but it looks like it will just work.

**Comment by refractalize** [comment]
hi @jsphadetula, just ran some tests and I've fixed it. I'll roll out a release shortly.

**Comment by jsphadetula** [comment]
Thanks for the prompt response 


Get Outlook for Android






On Tue, Jul 12, 2016 at 5:21 PM +0100, "Tim Macfarlane" <notifications@github.com> wrote:












hi @jsphadetula, just ran some tests and I've fixed it. I'll roll out a release shortly.

**Comment by refractalize** [comment]
hi @jsphadetula 2.11.0 is released with support for node `Buffer`. if you want streams you'll need to use the MS SQL driver direct as that can get complicated and is very specific to the driver.
