### ISSUE TITLE
Update table not working

### ISSUE THREAD

**Issue by softgandhi** [featurist/sworm#15]
Hi, I am using the following code to update the table:
```
var blog = db.model({ table: 'Blog' });
    req.body.statusId = 2;
    req.body.createdBy = req.body.authorId;
    var newBlog = blog(req.body);
    newBlog.save({ saved: true, modified: true, force: true }).then(function () {
        res.send({
            messge: "Blog Saved successfully"
        });
    }, function (err) {
        console.log(err);
        res.status(500).send(err);
    });
```
But its not updating the table.
Instead, it is trying to insert and throw the following exception:
 _Cannot insert explicit value for identity column in table 'Blog' when IDENTITY_INSERT is set to OFF._

I am new to sworm. Please suggest what could be wrong.

**Comment by refractalize** [comment]
hi @softgandhi 

The `saved` and `modified` options are passed to the model creation function, `blog()` in this case, not the `.save()` method. See [here](https://github.com/featurist/sworm#entities). If you do this you shouldn't need the `force` option on `save()`. So your code should look a bit like this:

```js
    var newBlog = blog(req.body, { saved: true, modified: true });
    newBlog.save().then(function () {
        res.send({
            messge: "Blog Saved successfully"
        });
    }, function (err) {
```

Let me know if that works..

**Comment by softgandhi** [comment]
Hi,
This worked for me.
Thank you very much. :)
