### ISSUE TITLE
Issue with Update/Insert Query

### ISSUE THREAD

**Issue by PadminiKarthika** [featurist/sworm#18]
Hello,

When I set saved:false and modified:true,  
even if the identity value exists in the table, an insert is attempted.
When saved:true and modified:true,
even if the identity value doesn't exist in the table, an update is attempted.
What I expect is :
"Update if identity exists already. Insert otherwise"
What options should I pass to the entity.

Regards,
Padmini

**Comment by refractalize** [comment]
thanks @PadminiKarthika, simplest thing you can do for now is

```js
var id = ... existing id, or undefined ...

var bob = person(
  {
    id: id,
    name: 'Bob'
  },
  // saved is true when the id is present, false otherwise
  {saved: !!id}
);

bob.save({force: true});
```

That being said, I think the API definitely needs something to make this more obvious. I'll take a look and get back to you. Let me know if the above works tho!

Thanks for getting in touch!

**Comment by PadminiKarthika** [comment]
Hi refractalize,

Thanks for building sworm in the first place.

This tweak works!!
But , I will be required to check whether the identity exists in the table or not , in order to set correct Boolean value to 'saved'.
Can't this happen automatically ?
Please suggest.

Regards,
Padmini

**Comment by refractalize** [comment]
@PadminiKarthika I've recently added `update`, `insert` and `upsert` to handle these cases more explicitly. I think you'll want to look at `upsert` in this case. See https://github.com/featurist/sworm#update-insert-upsert
