### ISSUE TITLE
Transaction support and LOB support

### ISSUE THREAD

**Issue by PadminiKarthika** [featurist/sworm#19]
Hi,

I donot have any issues to report.
These are indeed queries that I have on SWORM's features.
1.  Does SWORM support transactions ?
2. Does it support large objects - BLOB and CLOB ?
Please clarify.

Regards,
Padmini

**Comment by refractalize** [comment]
hi, turns out I had an old branch I was working for transactions: #21. Now merged and released in v2.16.0

**Comment by refractalize** [comment]
BLOBs, CLOBs, etc: There is support for putting node `Buffer` objects into your records, and these work with the underlying drivers. However, each driver may have additional support for streams and are often very implementation specific, so for the moment they're not in sworm. Happy to accept pull requests of this sort however.
