### ISSUE TITLE
Oracle Commit issue

### ISSUE THREAD

**Issue by PadminiKarthika** [featurist/sworm#20]
Hello,

I'm connecting to Oracle DB via SWORM.
I have set autocommit property to false.
Inspite of that I see that all the transactions that I perform are getting committed.
How to manage this?
How do I rollback transactions via SWORM ?

var oracleDriver = 'oracle';
var oracleDBConfig={
  user:'',
  password:'',
  connectString:'localhost/XE',
  pool:true,
  autocommit:false,
  options:{
    maxRows:1000
  }
}

Below snippet commits the INSERTED data 
// Create an entity instance
  var tableModel = db.model({table: 'test'});
  var flag = false;
  var rowInstance = tableModel({id:2, name:'TestData'},{saved:flag});
  return rowInstance.save({force: true}).then(function(){
    console.log('Create Successful');
    db.close();
  },function(err){
    console.log('Error ', err);
  });

Regards,
Padmini

**Comment by refractalize** [comment]
Hi @PadminiKarthika,

I've just made a change to the documentation explaining this.

> By default the driver is set to `autoCommit = true`, you can pass `options: { autoCommit: false}` to turn this off again.

Hopefully that clears it up.

**Comment by PadminiKarthika** [comment]
Hi @refractalize 

Thanks for clarifying..
Yeah I could prevent commit by setting autocommit to false.
How do I rollback transactions via SWORM.
Please suggest.

Regards,
Padmini
