### ISSUE TITLE
Transaction rollback doesn't work

### ISSUE THREAD

**Issue by PadminiKarthika** [featurist/sworm#22]
Hello,

Thanks for merging 'Transaction Support'code in the latest version.
However, Rollback doesn't work for me.

From debug logs,
I see that sworm invokes rollback. But I see that the inserted values are in the DB.
I have explicitly set 'autocommit' to false.
Please suggest as to why the values are not being rolled back

![ora_tx_rollback](https://cloud.githubusercontent.com/assets/22811855/19882088/f9c856c4-a030-11e6-965e-3e2f7fd50066.png)

My Code Snippet for INSERT operation:
var tableModel = db.model({table: 'sisp_ma5'});
 var flag = false;
db.transaction(() => {
    var rowInstance = tableModel({id:17, name:'Malappuram'},{saved:flag});
    return rowInstance.save({force: true}).then(() => {
      throw new Error ('Acho!');
    });
  });

**Comment by PadminiKarthika** [comment]
Hello  refractalize,

What is the stable SWORM  version with Transaction support ?
Please clarify.

Regards,
Padmini

**Comment by refractalize** [comment]
I think you need to pass auto commit in the options, as in: `options: { maxRows: 1000, autoCommit: false }`. Does that work?

**Comment by PadminiKarthika** [comment]
Hi ,

Thanks a bunch .
My DB Config looked like this:
var oracleDBConfig={
  user:'system',
  password:'Kavinn*143',
  connectString:'localhost/XE',
  pool:true,
  autoCommit:false,
  options:{
    maxRows:1000     
  }
}

I moved the autoCommit property under options. 
Rollback works like a charm now.
