### ISSUE TITLE
entity.identity() does not return the actual identity

### ISSUE THREAD

**Issue by cjhoward92** [featurist/sworm#24]
I am trying to get the id of newly persisted records using
```javascript
entity.identity()
```

however, it returns a random `INT` and not the `UNIQUEIDENTIFIER` I am using in MSSQL. My config looks like so

```javascript
const sworm = require('sworm')
const mssql = require('mssql')
const connectionConfig = require('../config')

const model = sworm.db(connectionConfig).model({ table: 'Complaints', id: 'id', idType: mssql.UniqueIdentifier });
```

I am not sure if sworm even supports non-integer identities in this regards yet. If this is supported, I would like some help, if not, then can we potentially add it as a new feature?

**Comment by cjhoward92** [comment]
Further investigation shows you are using `scope_identity()` with `mssql` which will work if we are generating an `INT IDENTITY` field. Your code in the mssql driver fields is like so:

```javascript
return this.query(query + "; select scope_identity() as " + id, params, options) // <- this is in 'insert'
```

Could we update this to return the new records identity? We could use [output](https://msdn.microsoft.com/en-us/library/ms177564.aspx) if you think it is a good idea.

**Comment by refractalize** [comment]
hi @cjhoward92, I'm looking into this now.

**Comment by refractalize** [comment]
@cjhoward92, i've added a `generatedId` option to the model options to select the means by which we get the generated id from the `insert into` statement, this can be either `scope_identity` or `output`. See the docs here: https://github.com/featurist/sworm#models. You'll want to use `output` for this case.

Let me know if this works for you.

**Comment by cjhoward92** [comment]
Hey that's awesome! Thanks!
