### ISSUE TITLE
UnhandledPromiseRejectionWarning even when .catch is specified

### ISSUE THREAD

**Issue by brettKgm** [featurist/sworm#26]
## Test code:

```
var notification = db.model(
  {
    table: 'notification',
    id: 'id'
  }
);

 // already exists in the db
var newItem = notification({ id: "0f0725b2-d331-4e53-b0ba-5c9fd9b30f25"});

return newItem.save().catch((err) => {
  return {error: err.message};
});
```

### return json:
>  "error": "Violation of PRIMARY KEY constraint 'PK__notifica__3213E83F52D484D2'. Cannot insert duplicate key in object 'dbo.notification'. The duplicate key value is (0f0725b2-d331-4e53-b0ba-5c9fd9b30f25)."

### console:
> No errors in console... maybe Status 500

### return json:
> "error": "Violation of PRIMARY KEY constraint 'PK__notifica__3213E83F52D484D2'. Cannot insert duplicate key in object 'dbo.notification'. The duplicate key value is (0f0725b2-d331-4e53-b0ba-5c9fd9b30f25)."

### console:
> (node:29938) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): RequestError: Violation of PRIMARY KEY constraint 'PK__notifica__3213E83F52D484D2'. Cannot insert duplicate key in object 'dbo.notification'. The duplicate key value is (0f0725b2-d331-4e53-b0ba-5c9fd9b30f25).
(node:29938) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by refractalize** [comment]
thanks @brettKgm for raising this, fix is in v3.3.0
