### ISSUE TITLE
OracleDB Update SQL Bug

### ISSUE THREAD

**Issue by JamesDLorence** [featurist/sworm#29]
In `oracleDriver.js` file, function `fieldsForObject` seems to only be returning the first key of the object which does not seem to be the expected behavior. This is making it so that what trying to do an `Update` no column are being listed since the first one listed for us in our key.

**Comment by refractalize** [comment]
Hi @JamesDLorence, thanks for raising this. Can you share the model definition, the object you're trying to update and perhaps the schema? Or as much as you can anyway.

I suspect you're talking about a table with compound keys?

Cheers

**Comment by refractalize** [comment]
A code snippet too would help, thanks

**Comment by JamesDLorence** [comment]
Sorry, I seem to have found the issue in my code. It was obvious but that's the difference between Friday afternoon and Monday morning.

**Comment by refractalize** [comment]
np - cheers
