### ISSUE TITLE
problem with call storedprocedure

### ISSUE THREAD

**Issue by isaacvitor** [featurist/sworm#3]
Query not works when call storedproc using varchar parameters. I'm trying this:

var strSQL = "exec myProcedure @bit, '@varchar', '@varchar' ";
AND
var strSQL = "exec myProcedure @bit, @varchar, @varchar ";

But only this way that works:
var strSQL = "exec myProcedure "+bitARG+", '"+varcharARG+"', '"+varcharARG+"'";

**Comment by refractalize** [comment]
Hi @isaacvitor, you may want to see this example: https://github.com/featurist/sworm#stored-procedure-example:

    db.query('myProcName @param1, @param2', {param1: 'a', param2: 'b'});

Notice that you don't use `exec`.

Although I can't wholly confirm this as I haven't got an SQL DB in front of me. If you're still having problems, perhaps you can share some more code and tell us which DB you're using?

**Comment by isaacvitor** [comment]
Tanks!
I had not seen this example. Now it's working!
