### ISSUE TITLE
Is there a way to specify the foreign key name when inserting an entity with an array of children?

### ISSUE THREAD

**Issue by cjhoward92** [featurist/sworm#31]
I have two tables: `Complaints` and `ComplaintDetails` where `ComplaintDetails` has a column `ComplaintId` that is the foreign key to the parent table. When I try to save the parent entity after adding a collection of children it tries to save the id to `complaint_id` which is obviously invalid.

Here is some sample code:

```Javascript
const db = sworm.db(connectionConfig)

const model = db.model({ 
    table: 'Complaints', 
    id: 'id', 
    idType: mssql.UniqueIdentifier, 
    generatedId: 'output'
})

const detailsModel= db.model({
    table: 'ComplaintDetails',
    id: 'ComplaintId'
})

function save(complaint, details) {
    let entity = model(complaint)
    let entity.details = function(saved) {
        let detailsEntities = _.map(details, (d) => {
                let m = detailsModel(d)
                m.complaint = saved
        })
        return detailsEntities
    }
    entity.save().then(() => {}).catch((e) => console.log(e))
}
```

My parent entity will save alright, but the children throw an error saying `Invalid column name 'complaint_id'`. Is there a way to map that child to parent action to a specific column name? Am I doing something wrong?

**Comment by refractalize** [comment]
hi @cjhoward92,

You can use `foreignKeyFor` ([docs here](https://github.com/featurist/sworm#models)):

```js
const model = db.model({ 
    table: 'Complaints', 
    id: 'id', 
    idType: mssql.UniqueIdentifier, // you won't need this, it's only used for oracle
    foreignKeyFor: (name) => name + 'Id',
    generatedId: 'output'
})
```

**Comment by cjhoward92** [comment]
Oh, great, thanks!
