### ISSUE TITLE
One-to-many: Why not insert outer_id into inner entity automatically?

### ISSUE THREAD

**Issue by arnebit** [featurist/sworm#33]
The documented example for one-to-many relationships is
> 
> ```
> var person = db.model({ table: 'people' });
> var address = db.model({ table: 'addresses' });
>  
> var bob = person({name: 'bob'});
> var jane = person({name: 'jane'});
>  
> var essert = address({
>   address: "15 Rue d'Essert",
>   people: [bob, jane]
> });
>  
> bob.address = essert;
> jane.address = essert;
> ```
>  

Why are the last two lines necessary? Later, it is stated that for

> an array of sworm entities
> ```
>   outer({
>     field: [
>       inner({ ... }),
>       inner({ ... })
>     ]
>   })
> ```
> - the outer entity is saved
> - ...
> - each of the entities in the array are saved

Why not between the steps, where I inserted the dots, have a step analoguously to the single-entity handling, namely
- the (outer) ID is placed in the inner entity's field_id field (see foreignKeyFor)
? The effect should be exactly what `[bob|jane].address = ...` above aim to achieve, and I have trouble coming up with a scenario where I would not want that done automatically (short of expanding the relationship to two-to-many, e.g. `bob.primaryAddress=essert; jane.secondaryAddress=essert;`, where `address.people` would probably cause futher headache down the road anyway).

**Comment by refractalize** [comment]
Yes, the Array form does require you to explicitly set the inner -> outer foreign key. There is the Function form that allows you to do it inline (this is the second example in the one-to-many section). 

I suppose the issue with setting `inner.outer = outer` automatically (if I understand you correctly) is that it's not always the case that `inner` has an `outer_id` column - we'd see SQL exceptions and we'd wonder who or what had set an `outer_id`. As you pointed out this wouldn't work with the two-to-many situation - how would you turn off this behaviour?

**Comment by arnebit** [comment]
As for turning it off, one could let `foreignKeyFor` return `false` if there is not foreign key column (in analogy to the `id` setting). ;-)

The "issue" here may be my lack of imagination for use cases where one would have _no_ foreign key (as opposed to a fixed number >1), but in any case I admit that it probably does not warrant a breaking change. :)

**Comment by refractalize** [comment]
Yeah - i agree there's virtually no reason at all to save an `outer = {inners: [inner1, inner2]}` without having `inner.outer`. Nevertheless, at this stage I think we should keep it explicit. Closing this - thanks for your input of course!
