### ISSUE TITLE
Oracle query issue

### ISSUE THREAD

**Issue by scalanode** [featurist/sworm#34]
Hi @refractalize, in oracleDriver.js, it seems that whenever i have a query which contains a count/rownum statement, the execute method throws an ugly error about the absence of a callback.
here's my sample model definition:

yes, it's a table with compound keys.
```
const ReportEntity = sworm.model({table: 'ABC, id: ['ID1, ID2, ID3']});
```

and here is my sample query:
```
 const options = {
              statement: true,
            };
return this.db.query('select count(*) from ABC where ABC.ID1 like (@ID1) AND ABC.ID2like (@ID2) AND ABC.ID3like (@ID3)',
                  {ID1: r.ID1, ID2: r.ID2, ID3: r.ID3}, options)
                  .then((result) => {
                    // logger.info(`db returned --> ${JSON.stringify(result)}`);
                    return result;
                  });
```
The point in oracleDriver.js which seems to be responsible is the else clause as the execute method in oracledb expects the last argument to be a callback which isn't being provided here:
```
var promise = options.statement || options.insert
        ? promisify(function (cb) {
          self.connection.execute(query, params || {}, options, cb)
        })
        _**: this.queryResultSet(query, params || {}, options)**_
```
Any thoughts?

**Comment by refractalize** [comment]
hi @scalanode

i can't seem to reproduce this from your example - a few questions:

* which version of oracledb and node are you using?
* I presume you're on latest sworm (v3.6.0)?
* what exactly is the error you're seeing?

**Comment by refractalize** [comment]
Compound keys should be an array of strings: `['ID1', 'ID2', 'ID3']` not a comma delimited string `['ID1, ID2, ID3']`.

Don't think this is the problem but worth worth pointing out!

**Comment by refractalize** [comment]
any more info on the schema would be helpful too, cheers!

**Comment by scalanode** [comment]
sorry for the delay... was on vacation.
node @ 4.4.3
oracledb @ 1.13.1
sworm @ latest

schema: a table with 13 fields(5 strings, 2 blobs, 2 boolean flags and a couple of dates) with 3 keys.

as i reverted back to using oracledb directly, hence i can now only try to remember about the
error: it was something about missing a callback as the last parameter. as the select query was neither a statement nor an insert. just a classic count/rownum lookup. maybe that was the issue.

thanks.
p.s: maybe sworm could also provide some interfaces for such lookup/rownum/count queries natively? though that would go against its being 'write-only' orm. cheers!
