### ISSUE TITLE
Is time for a CHANGELOG.md?

### ISSUE THREAD

**Issue by navarroaxel** [featurist/sworm#6]
Hi! I think we need a changelog, I really like this package but I need to know when a breaking change is released.

Is this possible?

Thanks!

**Comment by refractalize** [comment]
Hi @navarroaxel yes why not.

Curious, did you notice a breaking change? How do you normally specify the version in the `package.json`? I normally use exact versions these days, but people have different preferences so not for me to comment - just curious!

**Comment by navarroaxel** [comment]
No, I didn't notice any breaking change.

I'm always trying to use the last version of all my dependencies, I spend a few minutes to do a smoke test of my features when I do an update with a minor/major version of a package.

Also, I have curious about in what are you working.

**Comment by refractalize** [comment]
@navarroaxel I've started putting release notes into the [releases area](https://github.com/featurist/sworm/releases).
