### ISSUE TITLE
No exception on error?

### ISSUE THREAD

**Issue by artemave** [featurist/sworm#8]
I can see the error when I run with `DEBUG=sworm`, but I think it should be more visible (e.g. throw exception):

![screen shot 2016-02-22 at 16 35 30](https://cloud.githubusercontent.com/assets/23721/13224908/90889432-d982-11e5-8fa4-7565f648297b.png)

**Comment by refractalize** [comment]
can you reproduce this? is it not just a promise that hasn't been returned/handled?

**Comment by artemave** [comment]
That #9 you just fixed was the way to reproduce it ;)

**Comment by refractalize** [comment]
ok, closing for now - please reopen if you see it again.
